name: financier
description: "An Expenses tracking application"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0' # Updated SDK constraint

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8

  # For database
  drift: ^2.18.0
  sqlite3_flutter_libs: ^0.5.22
  path_provider: ^2.1.3
  path: ^1.9.0

  # State management
  provider: ^6.1.2

  # Date formatting
  intl: ^0.19.0

  # Excel export
  excel: ^4.0.2
  file_saver: ^0.3.0 # For saving the file on desktop
  google_fonts: ^6.3.2
  lucide_icons: ^0.257.0
  shared_preferences: ^2.5.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

  # Drift build runner
  drift_dev: ^2.18.0
  build_runner: ^2.4.11

flutter:
  uses-material-design: true
